{
 "title": "Kushion",
 "description": "Kubernetes cluster cost",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "domain", "label": "Domain", "query": "label_values(domain)" }
  ]
 },
 "panels": [
  {
   "title": "Compute cost by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "USD / hour" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_namespace) (korral_cluster_pod_cost_per_hour_dollars{domain=\"$domain\"})",
     "legendFormat": "{{pod_namespace}}"
    }
   ]
  },
  {
   "title": "Storage cost by namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "USD / hour" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_namespace) (korral_cluster_pod_volumes_cost_per_hour_dollars{domain=\"$domain\"})",
     "legendFormat": "{{pod_namespace}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "USD / hour" }
   ],
   "targets": [
    {
     "expr": "sum by (domain) (korral_cluster_node_cost_per_hour_dollars) + sum by (domain) (korral_cluster_k8s_cost_per_hour_dollars) + sum by (domain) (korral_cluster_node_volumes_cost_per_hour_dollars) + sum by (domain) (korral_cluster_loadbalancer_cost_per_hour_dollars) + sum by (domain) (korral_cluster_loadbalancer_traffic_cost_per_hour_dollars) + sum by (domain) (korral_cluster_orphaned_volumes_cost_per_hour_dollars) + sum by (domain) (korral_cluster_k8s_cost_per_hour_dollars)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Lost volumes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "USD / hour" }
   ],
   "targets": [
    {
     "expr": "sum by (domain) (korral_cluster_orphaned_volumes_cost_per_hour_dollars)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}