---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: korral
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korral
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services/proxy
  resourceNames:
  - korral:9897
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korral
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korral
subjects:
- kind: ServiceAccount
  name: korral
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: korral
  namespace: monitoring
  labels:
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: korral
      app.kubernetes.io/instance: korral
      app.kubernetes.io/component: exporter
  template:
    metadata:
      name: korral
      namespace: monitoring
      labels:
        app.kubernetes.io/name: korral
        app.kubernetes.io/instance: korral
        app.kubernetes.io/component: exporter
    spec:
      serviceAccountName: korral
      containers:
      - name: exporter
        image: agilestacks/korral
        # imagePullPolicy: Always
        args:
        - export
        - --check
        env:
        - name: KORRAL_PORT
          value: "9897"
        ports:
        - name: http
          containerPort: 9897
        readinessProbe:
          httpGet:
            path: /ping
            port: 9897
        livenessProbe:
          httpGet:
            path: /ping
            port: 9897
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: korral
  namespace: monitoring
  labels:
    # edit to set `domain` tag on exported metrics
    # important when monitoring multiple clusters
    domain: domain.com
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
spec:
  ports:
  - name: http
    port: 9897
    targetPort: 9897
    protocol: TCP
  selector:
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
