---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: korral
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korral
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korral
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korral
subjects:
- kind: ServiceAccount
  name: korral
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: korral
  namespace: monitoring
  labels:
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: korral
      app.kubernetes.io/instance: korral
      app.kubernetes.io/component: exporter
  template:
    metadata:
      name: korral
      namespace: monitoring
      labels:
        app.kubernetes.io/name: korral
        app.kubernetes.io/instance: korral
        app.kubernetes.io/component: exporter
    spec:
      serviceAccountName: korral
      containers:
      - name: exporter
        image: agilestacks/korral
        imagePullPolicy: Always
        args:
        - export
        - --check
        env:
        - name: KORRAL_PORT
          value: "9797"
        ports:
        - name: http
          containerPort: 9797
        readinessProbe:
          httpGet:
            path: /ping
            port: 9797
        livenessProbe:
          httpGet:
            path: /ping
            port: 9797
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: korral
  namespace: monitoring
  labels:
    # edit to set `domain` tag on exported metrics
    # important when monitoring multiple clusters
    domain: domain.com
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
spec:
  ports:
  - name: http
    port: 9797
    targetPort: 9797
    protocol: TCP
  selector:
    app.kubernetes.io/name: korral
    app.kubernetes.io/instance: korral
    app.kubernetes.io/component: exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # edit to match Prometheus custom resource serviceMonitorSelector
    # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/design.md
    release: prometheus-operator
  name: korral
  namespace: monitoring
spec:
  targetLabels:
  - domain
  endpoints:
  - port: http
    interval: "1m"
    scrapeTimeout: "20s"
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: korral
      app.kubernetes.io/instance: korral
      app.kubernetes.io/component: exporter
